### ISSUE TITLE
翻译中经常出现“布波能小姐”

### ISSUE THREAD

**Issue by EdrowsLuo** [tangqz/select-oblige-zh-machine-translation#1]
翻译中经常出现“布波能小姐”。
可能是因为没有性别相关的上下文，日语中对这方面又没做特别的区分，导致翻译经常出现这类错误。
是不是可以考虑在prompt中添加人物的性别信息。

**Comment by tangqz** [comment]
感谢反馈。
相应提示词已在 `trans.py` 中添加。
文本中出现的 ‘布波能小姐’ ‘凪小姐’ 均已修正，并发布在 v1.5 中。
